### ISSUE TITLE
Transactions issue, coins lost....

### ISSUE THREAD

**Issue by ticowork** [Bitcoinlightning/Bitcoin-Lightning#4]
We're having problems with the bltg wallet.
We have sent money to the exchange and the coins have been lost....

Status: 2792 confirmations
Date: 01/03/2018 20:30
To: BD9ApMr6XDBSjBEf8VMzGaHke17gPFxWYN
Debit: -1714.00 BLT
Transaction fee: -0.00008 BLT
Net amount: -1714.00008 BLT
Transaction ID: 23a9e751ba68d38b578a30cc9342c97e64aa0adfb4b133945b624f8511f8c1e3-000

Status: 2790 confirmations
Date: 01/03/2018 20:36
To: BD9ApMr6XDBSjBEf8VMzGaHke17gPFxWYN
Debit: -3010.99993 BLT
Transaction fee: -0.00001 BLT
Net amount: -3010.99994 BLT
Transaction ID: 85cb267d00add19f006ddb77a61a2761bc91f4b2afe77de1115c1a69d5aa8b96-000

**Comment by Bitcoinlightning** [comment]
Your transactions have never been broadcasted..
Please join support on discord, no coins can be lost
